### ISSUE TITLE
在我的电脑上无法通过命令下载模块

### ISSUE THREAD

**Issue by WeiyeJin** [dbsgw/wzk_auto#2]
我发现在我的电脑上无法通过 命令pip install requirements.txt,来下载模块，因此我使用目前最新的pycharm 23.1利用插件来下载模块，另外，我发现require里的hashlib已经是python标准库里的一部分了，在目前最新版本3.11.4中的已经可有可无，最后感谢学长，学长升本必成功，实习必签约，再次感谢学长的努力，比心！

**Comment by Mightnire** [comment]
你的命令缺了`-r`，因此无法下载。

完整的命令应该是：`pip install -r requirements.txt`

`hashlib`这个是因为当时不懂`requirements.txt`的使用，以为要把所有使用的python库都写在里面。闹笑话了。

~~[害，也感谢下我这个原作者呗。](https://github.com/dbsgw/wzk_auto/issues/3)~~  也祝学弟/学妹？学习顺利，找到合适的专业方向。（你也可以把你的代码传到这里来哦）

**Comment by dbsgw** [comment]
> 你的命令缺了`-r`，因此无法下载。
> 
> 完整的命令应该是：`pip install -r requirements.txt`
> 
> `hashlib`这个是因为当时不懂`requirements.txt`的使用，以为要把所有使用的python库都写在里面。闹笑话了。
> 
> ~[害，也感谢下我这个原作者呗。](https://github.com/dbsgw/wzk_auto/issues/3)~ 也祝学弟/学妹？学习顺利，找到合适的专业方向。（你也可以把你的代码传到这里来哦）

感谢原作者：我也是武软学子，参考项目直接cv过来了，抱歉，已备注项目来源
