### ISSUE TITLE
使用开源代码请注明来源

### ISSUE THREAD

**Issue by Mightnire** [dbsgw/wzk_auto#3]
您项目中的“微知库”文件夹与本人21年时的项目极为相似。

`https://github.com/dbsgw/wzk_auto/tree/main/%E5%BE%AE%E7%9F%A5%E5%BA%93`

`https://github.com/Mightnire/wzk_auto`

![截图未命名.png](https://img1.imgtp.com/2023/06/10/MOMsYH9w.png)

这个项目是本人初学Python时所写，虽然现在看来啥也不是。但在当时的情况下（啥也不会）也是废了一番功夫的。

总之，希望注明代码来源哦。

**Comment by dbsgw** [comment]
好的，我确认后再给您回复！  改了一些东西  晚点备注一下  ------------------------------------------------------------------
***@***.***>
日　期：2023年06月10日 22:52:08
***@***.***>
***@***.***>
主　题：[dbsgw/wzk_auto] 使用开源代码请注明来源 (Issue #3)

您项目中的“微知库”文件夹与本人21年时的项目极为相似。
https://github.com/dbsgw/wzk_auto/tree/main/%E5%BE%AE%E7%9F%A5%E5%BA%93
https://github.com/Mightnire/wzk_auto

这个项目是本人初学Python时所写，虽然现在看来啥也不是。但在当时的情况下（啥也不会）也是废了一番功夫的。
总之，希望注明代码来源哦。

**Comment by dbsgw** [comment]
> 您项目中的“微知库”文件夹与本人21年时的项目极为相似。
> 
> `https://github.com/dbsgw/wzk_auto/tree/main/%E5%BE%AE%E7%9F%A5%E5%BA%93`
> 
> `https://github.com/Mightnire/wzk_auto`
> 
> ![截图未命名.png](https://camo.githubusercontent.com/59d84b58c3d99612f004c6b8169afda5d3c21cb0569a51dd84e5d590772e2336/68747470733a2f2f696d67312e696d6774702e636f6d2f323032332f30362f31302f4d4f4d73594839772e706e67)
> 
> 这个项目是本人初学Python时所写，虽然现在看来啥也不是。但在当时的情况下（啥也不会）也是废了一番功夫的。
> 
> 总之，希望注明代码来源哦。
https://github.com/dbsgw/wzk_auto/issues/3#issue-1750999781

**Comment by dbsgw** [comment]
![image](https://github.com/dbsgw/wzk_auto/assets/69408664/c7477c71-a5de-4ec6-938e-c5422fbe783b)
